# Generated by Django 4.1.7 on 2023-05-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='static/profile_picture/UtenteDefault.png', upload_to='profile_pictures/'),
        ),
    ]
